<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-18 09:57
=======
# Generated by Django 4.2.7 on 2023-11-18 08:35
>>>>>>> c640e29b683d6ffdd9748a4365ea6d3e0cfa31ec

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
<<<<<<< HEAD

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
=======
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> c640e29b683d6ffdd9748a4365ea6d3e0cfa31ec
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Shift',
            fields=[
                ('Shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('num_hours', models.IntegerField()),
                ('num_people', models.IntegerField()),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.group')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name="Shift",
            fields=[
                ("Shift_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("num_hours", models.IntegerField()),
                ("num_people", models.IntegerField()),
                (
                    "group_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shift.shift"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
>>>>>>> c640e29b683d6ffdd9748a4365ea6d3e0cfa31ec
            ],
        ),
    ]
