name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
        
    - name: Python Django Coverage GitHub Action Unmanaged
      # You may pin to the exact commit or the version.
      # uses: MateuszKuba/python-django-coverage-unamangedmodels@c8a0a838703cabc37dd755f9618d36551b9cda9f
      uses: MateuszKuba/python-django-coverage-unamangedmodels@0.1
      with:
        # Application
        django-app: bookga
        # Minimum allowed code coverage
        minimum-coverage: '90'
